Repository nv-legate/cunumeric, pull requests merged in 2022-12, with the labels that each got.

#723 Fix build under CUDA 11.8
  src/cunumeric/random/randutil/generator.cuh
Labels: category:task

#719 Enhance test_solve.py and test_matrix_power.py
  cunumeric/linalg/linalg.py
  tests/integration/test_matrix_power.py
  tests/integration/test_solve.py
Labels: category:task

#730 Enhance test_dot.py and test_multi_dot.py
  tests/integration/test_dot.py
  tests/integration/test_multi_dot.py
Labels: category:task

#727 guard all2all from empty transfer
  src/cunumeric/sort/sort.cu
Labels: category:bug-fix

#741 Clean up the basic build instructions
  BUILD.md
  README.md
Labels: category:improvement

#567 Refactor benchmarks
  examples/benchmark.py
  examples/black_scholes.py
  examples/cg.py
  examples/einsum.py
  examples/gemm.py
  examples/indexing_routines.py
  examples/jacobi.py
  examples/kmeans.py
  examples/kmeans_slow.py
  examples/kmeans_sort.py
  examples/linreg.py
  examples/logreg.py
  examples/lstm_backward.py
  examples/lstm_forward.py
  examples/lstm_full.py
  examples/richardson_lucy.py
  examples/scan.py
  examples/solve.py
  examples/sort.py
  examples/stencil.py
  examples/wgrad.py
Labels: category:improvement

#740 src/cunumeric/item: add openmp variants for write/read tasks
  src/cunumeric/item/read.h
  src/cunumeric/item/write.h
Labels: category:bug-fix

#743 Add back NaN checks to some benchmarks
  examples/jacobi.py
  examples/logreg.py
Labels: category:task

#745 Fix CI failures due to numpy 1.24 upgrade
  cunumeric/eager.py
  tests/integration/test_ndim.py
Labels: category:bug-fix

#731 Improving performance for some special cases of advanced indexing
  cunumeric/deferred.py
  src/cunumeric/index/putmask_template.inl
  tests/integration/test_advanced_indexing.py
Labels: category:improvement
