Repository nv-legate/cunumeric, pull requests merged in 2022-11, with the labels that each got.

#671 Enhance test_put_along_axis, test_take_along_axis.
  tests/integration/test_put_along_axis.py
  tests/integration/test_take_along_axis.py
  tests/integration/utils/generators.py
Labels: category:task

#675 Eliminate empty kernel launch in `cunumeric.unique`
  src/cunumeric/set/unique.cu
  tests/integration/test_unique.py
Labels: category:bug-fix

#674 Some quality-of-life changes
  src/cunumeric/binary/binary_op_util.h
  src/cunumeric/omp_help.h
  src/cunumeric/scan/scan_local_template.inl
  src/cunumeric/unary/convert_template.inl
  src/cunumeric/unary/convert_util.h
  src/cunumeric/unary/unary_op_util.h
  src/cunumeric/unary/unary_red_util.h
Labels: category:task

#676 Mark sort and unique variants as concurrent
  src/cunumeric/set/unique.cc
  src/cunumeric/sort/sort.cc
Labels: category:task

#670 Make `install.py` reconfigure editable installs when build type changes
  install.py
  scripts/build-install.sh
  scripts/build-no-install.sh
  scripts/build-separately-no-install.sh
  scripts/build-with-legate-no-install.sh
  scripts/build-with-legate-separately-no-install.sh
  scripts/util/uninstall-global-legion-legate-core-and-cunumeric.sh
Labels: category:bug-fix

#678 Configure test overrides in the project test.py
  test.py
Labels: category:task

#672 add test case for test_compress.py and test_extract.py
  cunumeric/array.py
  tests/integration/test_compress.py
  tests/integration/test_extract.py
Labels: category:task

#688 Mypy fix
  cunumeric/config.py
  cunumeric/random/bitgenerator.py
Labels: category:task

#666 Test case for 0D region-backed stores
  tests/integration/test_0d_store.py
Labels: category:task

#686 Fix for #684
  src/cunumeric/set/unique.cu
  tests/integration/test_unique.py
Labels: category:bug-fix

#689 Add missing put method to docs
  docs/cunumeric/source/api/_ndarray.rst
  docs/cunumeric/source/api/ndarray.rst
Labels: category:task

#680 Enhance test_linspace.py and test_swapaxes.py
  tests/integration/test_linspace.py
  tests/integration/test_swapaxes.py
Labels: category:task

#690 Handle complex dtypes in __legate_data_interface__
  cunumeric/array.py
  tests/integration/test_data_interface.py
Labels: category:task

#679 Log operator names of unary and binary operations using annotations
  cunumeric/deferred.py
Labels: category:improvement

#697 Add CI job to build docs
  .github/workflows/ci.yml
Labels: category:task

#694 add negative test case for test_convolve.py and test_astype.py
  tests/integration/test_astype.py
  tests/integration/test_convolve.py
Labels: category:task

#687 Print build start and end times in a conda build
  conda/conda-build/build.sh
Labels: category:task

#667 Implementing Putmask
  cunumeric/config.py
  cunumeric/deferred.py
  cunumeric/eager.py
  cunumeric/module.py
  cunumeric/thunk.py
  cunumeric_cpp.cmake
  docs/cunumeric/source/api/indexing.rst
  src/cunumeric/cunumeric_c.h
  src/cunumeric/execution_policy/indexing/parallel_loop.cuh
  src/cunumeric/execution_policy/indexing/parallel_loop.h
  src/cunumeric/execution_policy/indexing/parallel_loop_omp.h
  src/cunumeric/index/putmask.cc
  src/cunumeric/index/putmask.cu
  src/cunumeric/index/putmask.h
  src/cunumeric/index/putmask_omp.cc
  src/cunumeric/index/putmask_template.inl
  tests/integration/test_putmask.py
  tests/unit/cunumeric/test_config.py
Labels: category:new-feature

#696 Enhance test_index_routines.py and test_reshape.py
  tests/integration/test_index_routines.py
  tests/integration/test_reshape.py
Labels: category:task

#701 Minor test QOL improvements: make cunumeric imports consistent
  tests/integration/test_array_dunders.py
  tests/integration/test_diag_indices.py
  tests/integration/test_einsum.py
  tests/integration/test_einsum_path.py
  tests/integration/test_indices.py
  tests/integration/test_ingest.py
  tests/integration/test_lstm_simple_forward.py
  tests/integration/test_matrix_power.py
  tests/integration/test_min_on_gpu.py
  tests/integration/test_moveaxis.py
  tests/integration/test_multi_dot.py
  tests/integration/test_norm.py
  tests/integration/test_outer.py
  tests/integration/test_random_creation.py
  tests/integration/test_reduction_axis.py
  tests/integration/test_vdot.py
  tests/integration/test_window.py
  tests/integration/utils/contractions.py
Labels: category:task

#698 Sync supported-dtype check between utils.py and runtime.py
  cunumeric/runtime.py
  cunumeric/utils.py
  tests/integration/test_data_interface.py
  tests/unit/cunumeric/test_utils.py
Labels: category:task

#699 Also check shape and dtype in allclose
  cunumeric/linalg/linalg.py
  cunumeric/module.py
  tests/integration/test_einsum.py
  tests/integration/test_solve.py
  tests/integration/utils/comparisons.py
  tests/integration/utils/contractions.py
Labels: category:task

#705 Regenerate `install_info.py` on every build
  CMakeLists.txt
  cmake/generate_install_info_py.cmake
  cunumeric_python.cmake
  scripts/build-install.sh
  scripts/build-no-install.sh
  scripts/build-separately-no-install.sh
  scripts/build-with-legate-no-install.sh
  scripts/build-with-legate-separately-no-install.sh
Labels: category:improvement

#711 More argument checks for `bincount`
  cunumeric/module.py
Labels: category:bug-fix

#713 Fix a typo in unique.cu indexing
  src/cunumeric/set/unique.cu
Labels: category:bug-fix

#706 Fixes for buffer allocations
  .github/workflows/ci.yml
  cunumeric/config.py
  src/cunumeric/cunumeric.cc
  src/cunumeric/cunumeric.h
  src/cunumeric/cunumeric_c.h
  src/cunumeric/index/repeat_omp.cc
  src/cunumeric/index/repeat_template.inl
  src/cunumeric/mapper.cc
  src/cunumeric/matrix/contract_omp.cc
  src/cunumeric/matrix/matmul_omp.cc
  src/cunumeric/matrix/matvecmul_omp.cc
  src/cunumeric/matrix/solve_cpu.inl
  src/cunumeric/matrix/util.cc
  src/cunumeric/matrix/util_omp.cc
  src/cunumeric/matrix/util_omp.h
  src/cunumeric/search/argwhere_template.inl
  src/cunumeric/search/nonzero.cc
  src/cunumeric/search/nonzero.cu
  src/cunumeric/search/nonzero_omp.cc
  src/cunumeric/search/nonzero_template.inl
  src/cunumeric/set/unique.cc
  src/cunumeric/set/unique.cu
  src/cunumeric/set/unique_omp.cc
  src/cunumeric/set/unique_reduce.cc
  src/cunumeric/set/unique_reduce_template.inl
  src/cunumeric/set/unique_template.inl
  src/cunumeric/sort/sort.cu
  tests/unit/cunumeric/test_config.py
Labels: category:improvement

#714 Don't use cmake 3.25.0 in build-isolation mode
  pyproject.toml
Labels: category:task

#716 Minor type improvements
  cunumeric/__init__.py
  cunumeric/array.py
  cunumeric/coverage.py
  cunumeric/deferred.py
  cunumeric/eager.py
  cunumeric/linalg/linalg.py
  cunumeric/module.py
  cunumeric/runtime.py
  cunumeric/sort.py
  cunumeric/utils.py
  pyproject.toml
Labels: category:task

#715 Update Availability annotations
  cunumeric/array.py
  cunumeric/logic.py
  cunumeric/random/random.py
Labels: category:task

#717 Enhance test_where.py and test_atleast_nd.py
  tests/integration/test_atleast_nd.py
  tests/integration/test_where.py
Labels: category:task

#708 Testcase enhance for test_bincount.py
  tests/integration/test_bincount.py
  tests/integration/test_cholesky.py
Labels: category:task
