Repository nv-legate/cunumeric, pull requests merged in 2022-09, with the labels that each got.

#566 fix error print in test_unary_ufunc
  tests/integration/test_unary_ufunc.py
Labels: category:bug-fix

#547 Use conda build in CI
  .github/workflows/ci.yml
  conda/conda-build/meta.yaml
  cunumeric/array.py
  cunumeric/config.py
  cunumeric/deferred.py
  install.py
  pyproject.toml
Labels: category:task

#572 src/cunumeric/search: make nonzero not always allocate SYS_MEM buffers
  src/cunumeric/search/nonzero_omp.cc
  src/cunumeric/set/unique_omp.cc
Labels: category:bug-fix

#502 Add NAN handling to convert() needed for some prefix routines with integer outputs.
  cunumeric/array.py
  cunumeric/config.py
  cunumeric/deferred.py
  cunumeric/eager.py
  cunumeric/thunk.py
  src/cunumeric/cunumeric_c.h
  src/cunumeric/scan/scan_global_util.h
  src/cunumeric/unary/convert.cc
  src/cunumeric/unary/convert.cu
  src/cunumeric/unary/convert.h
  src/cunumeric/unary/convert_omp.cc
  src/cunumeric/unary/convert_template.inl
  src/cunumeric/unary/convert_util.h
  tests/integration/test_scan.py
Labels: category:new-feature

#545 add negative test case in test_array_split.py
  cunumeric/module.py
  tests/integration/test_array_split.py
  tests/integration/utils/utils.py
Labels: category:task

#574 Fixing logic for slicing
  cunumeric/deferred.py
  tests/integration/test_advanced_indexing.py
  tests/integration/test_get_item.py
Labels: category:bug-fix

#575 add some test cases for test_arg_reduce.py
  cunumeric/array.py
  tests/integration/test_arg_reduce.py
Labels: category:task

#579 Testcase-add test cases for test_flip and test_indices
  cunumeric/deferred.py
  tests/integration/test_flip.py
  tests/integration/test_indices.py
Labels: category:task

#568 Single processor implementation for `linalg.solve`
  cunumeric/config.py
  cunumeric/deferred.py
  cunumeric/eager.py
  cunumeric/linalg/cholesky.py
  cunumeric/linalg/linalg.py
  cunumeric/linalg/solve.py
  cunumeric/thunk.py
  docs/cunumeric/source/api/linalg.rst
  examples/solve.py
  src/cunumeric.mk
  src/cunumeric/cunumeric_c.h
  src/cunumeric/mapper.cc
  src/cunumeric/matrix/solve.cc
  src/cunumeric/matrix/solve.cu
  src/cunumeric/matrix/solve.h
  src/cunumeric/matrix/solve_cpu.inl
  src/cunumeric/matrix/solve_omp.cc
  src/cunumeric/matrix/solve_template.inl
  tests/integration/test_array_dunders.py
  tests/integration/test_solve.py
  tests/unit/cunumeric/test_config.py
Labels: category:new-feature

#573 Refactor scalar reductions to use common execution policy
  src/cunumeric/execution_policy/reduction/scalar_reduction.cuh
  src/cunumeric/execution_policy/reduction/scalar_reduction.h
  src/cunumeric/execution_policy/reduction/scalar_reduction_omp.h
  src/cunumeric/unary/scalar_unary_red.cc
  src/cunumeric/unary/scalar_unary_red.cu
  src/cunumeric/unary/scalar_unary_red_omp.cc
  src/cunumeric/unary/scalar_unary_red_template.inl
  src/cunumeric/unary/unary_red_util.h
Labels: category:improvement

#586 Sanitize `k` for the `eye` operator
  cunumeric/module.py
Labels: category:bug-fix

#585 Fix `linalg.solve` when inputs are scalars
  src/cunumeric/matrix/solve_template.inl
  tests/integration/test_solve.py
Labels: category:bug-fix

#578 Enhance test_block.py and test_eye.py
  tests/integration/test_block.py
  tests/integration/test_eye.py
  tests/integration/utils/utils.py
Labels: category:task

#603 Add `linalg.solve` to the cmake build
  cunumeric_cpp.cmake
Labels: category:bug-fix

#588 Testcase add test cases for test_fill.py and test_ndim.py
  cunumeric/module.py
  tests/integration/test_fill.py
  tests/integration/test_ndim.py
Labels: category:task

#607 Delay label checking on fresh PRs
  .github/workflows/require-labels.yml
Labels: category:task

#604 Use Legion Fills when possible
  cunumeric/deferred.py
Labels: category:improvement

#610 Support building with GASNet-Ex and MPI backends
  README.md
  cunumeric_cpp.cmake
  install.py
Labels: category:improvement

#614 updating documentation
  docs/cunumeric/source/index.rst
  docs/cunumeric/source/versions.rst
Labels: documentation, category:task, category:documentation

#596 Provenance tracking for cuNumeric operators
  cunumeric/coverage.py
  cunumeric/utils.py
Labels: category:new-feature

#616 Invoke eye with read-write privilege, not write-discard
  cunumeric/deferred.py
Labels: category:bug-fix

#606 Fix a bug in scalar reduction launching kernels with empty domains
  src/cunumeric/execution_policy/reduction/scalar_reduction.cuh
Labels: category:bug-fix

#592 Fix tests utils to make --directory work correctly.
  tests/_utils/config.py
  tests/_utils/stages/test_stage.py
  tests/_utils/ui.py
Labels: category:bug-fix

#594 Fix a compiler warning
  src/cunumeric/unary/unary_op_util.h
Labels: category:improvement

#609 Enhance test_diag_indices.py and test_flatten.py.
  tests/integration/test_append.py
  tests/integration/test_array_split.py
  tests/integration/test_block.py
  tests/integration/test_diag_indices.py
  tests/integration/test_eye.py
  tests/integration/test_flatten.py
  tests/integration/utils/utils.py
Labels: category:task

#617 cuNumeric doesn't need nested provenance tracking
  cunumeric/coverage.py
Labels: category:improvement

#618 Add RuntimeError exception to legate.time
  examples/cg.py
  examples/einsum.py
  examples/jacobi.py
  examples/logreg.py
  examples/sort.py
  examples/stencil.py
Labels: category:bug-fix

#621 Stop instantiating min and max reduction ops for complex types
  src/cunumeric/arg.cc
  src/cunumeric/cunumeric.cu
  src/cunumeric/unary/unary_red_util.h
Labels: category:task

#608 Mark temporary conversion outputs as linear for eager storage recycling
  cunumeric/_ufunc/ufunc.py
  cunumeric/array.py
  cunumeric/deferred.py
  cunumeric/eager.py
  cunumeric/thunk.py
Labels: category:improvement

#619 Make the negative test on `fill` robust across Python versions
  tests/integration/test_fill.py
Labels: category:bug-fix

#622 Enhance mask_indices and move_axis
  tests/integration/test_mask_indices.py
  tests/integration/test_moveaxis.py
Labels: category:task

#623 Run CI every 4 hours
  .github/workflows/ci.yml
Labels: category:task

#620 src/cunumeric/matrix: stop including coll.h in solve_template.inl
  src/cunumeric/matrix/solve_template.inl
Labels: category:bug-fix

#637 src/cunumeric/matrix: stop including coll.h in solve_template.inl (#620)
  src/cunumeric/matrix/solve_template.inl
Labels: category:task

#635 Add missing docs symlink
  docs/cunumeric/source/BUILD.md
Labels: category:bug-fix, category:documentation
