Repository nv-legate/cunumeric, pull requests merged in 2022-10, with the labels that each got.

#641 Adjust the schedule of the CI runs
  .github/workflows/ci.yml
Labels: category:task

#627 Move test driver code to legate.core
  test.py
  tests/_utils/__init__.py
  tests/_utils/args.py
  tests/_utils/config.py
  tests/_utils/logger.py
  tests/_utils/stages/__init__.py
  tests/_utils/stages/_linux/__init__.py
  tests/_utils/stages/_linux/cpu.py
  tests/_utils/stages/_linux/eager.py
  tests/_utils/stages/_linux/gpu.py
  tests/_utils/stages/_linux/omp.py
  tests/_utils/stages/_osx/__init__.py
  tests/_utils/stages/_osx/cpu.py
  tests/_utils/stages/_osx/eager.py
  tests/_utils/stages/_osx/gpu.py
  tests/_utils/stages/_osx/omp.py
  tests/_utils/stages/test_stage.py
  tests/_utils/stages/util.py
  tests/_utils/system.py
  tests/_utils/test_plan.py
  tests/_utils/tests/__init__.py
  tests/_utils/tests/stages/__init__.py
  tests/_utils/tests/stages/_linux/__init__.py
  tests/_utils/tests/stages/_linux/test_cpu.py
  tests/_utils/tests/stages/_linux/test_eager.py
  tests/_utils/tests/stages/_linux/test_gpu.py
  tests/_utils/tests/stages/_linux/test_omp.py
  tests/_utils/tests/stages/test_test_stage.py
  tests/_utils/tests/stages/test_util.py
  tests/_utils/tests/test___init__.py
  tests/_utils/tests/test_args.py
  tests/_utils/tests/test_config.py
  tests/_utils/tests/test_logger.py
  tests/_utils/tests/test_system.py
  tests/_utils/tests/test_types.py
  tests/_utils/tests/test_ui.py
  tests/_utils/types.py
  tests/_utils/ui.py
Labels: category:improvement

#648 Make the code compile with bounds checks
  src/cunumeric/sort/sort_cpu.inl
  src/cunumeric/unary/scalar_unary_red_template.inl
  src/cunumeric/unary/unary_red.cu
Labels: category:bug-fix

#605 Add GitHub changelog configuration
  .github/release.yml
Labels: category:task

#646 MatVec & MatVecMul use reduction stores, not outputs
  src/cunumeric/mapper.cc
Labels: category:bug-fix

#615 Remove leftover files from old build
  src/Makefile
  src/cunumeric.mk
  src/cunumeric/random/random.mk
  src/cunumeric/sort/sort.mk
Labels: category:task

#602 Set default generator based on whether ninja is available
  install.py
Labels: category:bug-fix

#640 Allow args to be passed by position and name in auto_convert
  cunumeric/array.py
  cunumeric/deferred.py
Labels: category:bug-fix

#580 Force positive values for log and sqrt tests
  tests/integration/test_unary_ufunc.py
Labels: category:bug-fix

#658 Enhance test_tri*.py.
  tests/integration/test_tri.py
  tests/integration/test_trilu.py
  tests/integration/test_trilu_indices.py
  tests/integration/utils/utils.py
Labels: category:task

#656 Remove --install-dir option
  install.py
Labels: category:improvement

#661 Fix missing legate-core run requirement
  conda/conda-build/meta.yaml
Labels: bug, category:task

#582 Implementing PUT routine
  cunumeric/array.py
  cunumeric/deferred.py
  cunumeric/eager.py
  cunumeric/module.py
  cunumeric/thunk.py
  docs/cunumeric/source/api/indexing.rst
  src/cunumeric/index/wrap.cc
  src/cunumeric/index/wrap.cu
  src/cunumeric/index/wrap.h
  src/cunumeric/index/wrap_omp.cc
  src/cunumeric/index/wrap_template.inl
  src/cunumeric/index/zip.cu
  src/cunumeric/index/zip.h
  tests/integration/test_put.py
Labels: category:new-feature

#663 Update version number
  CMakeLists.txt
Labels: category:task

#662 Testcase add test cases for test_squeeze.py and test_transpose.py
  tests/integration/test_squeeze.py
  tests/integration/test_transpose.py
Labels: category:task

#651 Updates for new script-based conda env generation
  BUILD.md
  README.md
  conda/environment-test-3.10.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
Labels: category:improvement

#669 Update upload artifact action version
  .github/workflows/ci.yml
Labels: category:task

#665 Following on comments for PUT
  cunumeric/array.py
  cunumeric/deferred.py
  cunumeric/eager.py
  cunumeric/thunk.py
  src/cunumeric/index/wrap.cc
  src/cunumeric/index/wrap.cu
  src/cunumeric/index/wrap.h
  src/cunumeric/index/wrap_omp.cc
  src/cunumeric/index/wrap_template.inl
  src/cunumeric/index/zip.h
  src/cunumeric/index/zip_omp.cc
Labels: category:task
