Repository nv-legate/cunumeric, pull requests merged in 2023-10, with the labels that each got.

#1056 Satisfy new flake8 type check rules
  cunumeric/array.py
  cunumeric/module.py
  cunumeric/utils.py
  tests/integration/test_prod.py
  tests/integration/test_reduction.py
  tests/integration/test_squeeze.py
  tests/unit/cunumeric/test_coverage.py
Labels: category:improvement

#593 Added variance as a unary reduction
  cunumeric/array.py
  cunumeric/config.py
  cunumeric/deferred.py
  cunumeric/eager.py
  cunumeric/module.py
  cunumeric/utils.py
  docs/cunumeric/source/api/ndarray.rst
  docs/cunumeric/source/api/statistics.rst
  src/cunumeric/cunumeric_c.h
  src/cunumeric/unary/scalar_unary_red_template.inl
  src/cunumeric/unary/unary_red_util.h
  tests/integration/test_stats.py
Labels: category:new-feature

#1062 Create bug_report.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: category:task
