Repository nv-legate/cunumeric, pull requests merged in 2023-12, with the labels that each got.

#1098 Update version
  CMakeLists.txt
  cmake/versions.json
Labels: category:task

#1061 Supporting "where" for unary operations
  cunumeric/_ufunc/ufunc.py
  cunumeric/array.py
  cunumeric/deferred.py
  cunumeric/eager.py
  cunumeric/linalg/cholesky.py
  cunumeric/module.py
  docs/cunumeric/source/api/statistics.rst
  src/cunumeric/unary/scalar_unary_red.cc
  src/cunumeric/unary/scalar_unary_red.cu
  src/cunumeric/unary/scalar_unary_red.h
  src/cunumeric/unary/scalar_unary_red_omp.cc
  src/cunumeric/unary/scalar_unary_red_template.inl
  src/cunumeric/unary/unary_red.cc
  src/cunumeric/unary/unary_red.cu
  src/cunumeric/unary/unary_red.h
  src/cunumeric/unary/unary_red_omp.cc
  src/cunumeric/unary/unary_red_template.inl
  tests/integration/test_logical.py
  tests/integration/test_mean.py
  tests/integration/test_nan_reduction.py
  tests/integration/test_nanmean.py
  tests/integration/test_prod.py
  tests/integration/test_reduction.py
  tests/integration/test_stats.py
Labels: category:new-feature

#1100 add more datatype for input in test_binary_ufunc.py
  tests/integration/test_binary_ufunc.py
Labels: category:task

#1066 Support np.select operation
  cunumeric/config.py
  cunumeric/deferred.py
  cunumeric/eager.py
  cunumeric/module.py
  cunumeric/thunk.py
  cunumeric_cpp.cmake
  docs/cunumeric/source/api/indexing.rst
  src/cunumeric/cunumeric_c.h
  src/cunumeric/index/select.cc
  src/cunumeric/index/select.cu
  src/cunumeric/index/select.h
  src/cunumeric/index/select_omp.cc
  src/cunumeric/index/select_template.inl
  tests/integration/test_index_routines.py
  tests/unit/cunumeric/test_config.py
Labels: category:new-feature

#1102 Add Cmake flag to ensure we're propagating thread_count
  install.py
Labels: category:bug-fix
