Repository nv-legate/cunumeric, pull requests merged in 2023-04, with the labels that each got.

#861 Add tests for amax, amin and mean.
  cunumeric/deferred.py
  tests/integration/test_amax_amin.py
  tests/integration/test_mean.py
Labels: category:task

#873 Switch to quarterly updates of pre-commit hooks
  .pre-commit-config.yaml
Labels: category:task

#850 Separate cunumeric CI from legate.core CI
  .github/workflows/ci.yml
  cmake/versions.json
  cunumeric_cpp.cmake
Labels: category:task

#875 Note new minimum CUDA requirements for conda packages
  README.md
Labels: category:documentation

#877 Add array/asarray test and enhance outer test
  tests/integration/test_array.py
  tests/integration/test_outer.py
Labels: category:task

#876 Changes for the new registration API
  cmake/versions.json
  cunumeric/config.py
  src/cunumeric/cunumeric.cc
  src/cunumeric/cunumeric.h
  tests/unit/cunumeric/test_config.py
Labels: category:task

#880 Avoid following compiler symlinks
  CMakeLists.txt
  cmake/thirdparty/get_tblis.cmake
Labels: category:bug-fix

#878 Changes for the new mapper API
  cmake/versions.json
  src/cunumeric/cunumeric.cc
  src/cunumeric/cunumeric_c.h
  src/cunumeric/mapper.h
Labels: category:task

#886 Start using `LibraryContext*`
  cmake/versions.json
  src/cunumeric/arg.cc
  src/cunumeric/cunumeric.cc
  src/cunumeric/cunumeric.cu
Labels: category:task

#888 Bump up the legate core commit hash to be on the latest legion
  cmake/versions.json
Labels: category:task

#889 Fix for some binary operators on float16
  src/cunumeric/binary/binary_op_util.h
Labels: category:bug-fix

#891 Update the legate core commit hash
  cmake/versions.json
Labels: category:task

#890 WAR for TBLIS compiler detection while upstream PR is pending
  cmake/thirdparty/get_tblis.cmake
Labels: category:bug-fix

#881 add test_clip.py and test_identity.py
  tests/integration/test_clip.py
  tests/integration/test_identity.py
Labels: category:task

#900 Bump legate.core version to get legion fixes for CI hang
  cmake/versions.json
Labels: category:task

#893 Document cpp / read-only env config settings
  cunumeric/settings.py
  src/cunumeric/mapper.cc
  src/cunumeric/mapper.h
  src/env_defaults.h
  tests/unit/cunumeric/test_settings.py
Labels: category:task

#892 Improve code coverage in array_split/unpackbits/place
  tests/integration/test_array_split.py
  tests/integration/test_bits.py
  tests/integration/test_extract.py
Labels: category:task

#898 Improve code coverage for cunumeric.bincount
  cunumeric/module.py
  tests/integration/test_bincount.py
Labels: category:task

#906 Skip codebase checks in CI
  tests/unit/cunumeric/test_settings.py
Labels: category:task

#910 Fix array API(#885).
  cunumeric/module.py
  tests/integration/test_array.py
Labels: category:bug-fix

#909 Add ops-bot config file
  .github/ops-bot.yaml
Labels: category:improvement
