Repository nv-legate/cunumeric, pull requests merged in 2023-02, with the labels that each got.

#776 Update label action to v3
  .github/workflows/require-labels.yml
Labels: category:task

#777 Remove unsuccessful label delay attempt
  .github/workflows/require-labels.yml
Labels: category:task

#769 Enhance test_matmul.py and test_norm.py
  tests/integration/test_matmul.py
  tests/integration/test_norm.py
Labels: category:task

#791 Enhance test_vdot.py and test_window.py
  tests/integration/test_vdot.py
  tests/integration/test_window.py
Labels: category:task

#787 Testcase enhance test_fill_diagonal and test_searchsorted
  tests/integration/test_fill_diagonal.py
  tests/integration/test_searchsorted.py
Labels: category:task

#780 Use `thrust::cuda::par_nosync` if available
  src/cunumeric/index/advanced_indexing.cu
  src/cunumeric/index/repeat.cu
  src/cunumeric/scan/scan_global.cu
  src/cunumeric/scan/scan_local.cu
  src/cunumeric/search/nonzero.cuh
  src/cunumeric/set/unique.cu
  src/cunumeric/sort/sort.cu
  src/cunumeric/sort/thrust_sort.cuh
  src/cunumeric/utilities/thrust_util.h
Labels: category:improvement

#799 "Move RC command line args to env var / settings"
  cunumeric/__init__.py
  cunumeric/args.py
  cunumeric/coverage.py
  cunumeric/linalg/cholesky.py
  cunumeric/runtime.py
  cunumeric/settings.py
  tests/unit/cunumeric/test_coverage.py
  tests/unit/cunumeric/test_settings.py
Labels: category:task

#800 Forward parallelism level to dependencies when building with cmake in conda
  conda/conda-build/build.sh
Labels: category:task

#806 Add documentation category label
  .github/workflows/require-labels.yml
Labels: category:task

#807 Enhance test_take.py and test_put.py
  cunumeric/array.py
  tests/integration/test_put.py
  tests/integration/test_take.py
Labels: category:task

#816 Add hopper to CUDA architectures
  cmake/Modules/cuda_arch_helpers.cmake
Labels: category:task

#810 Don't silently ignore non-existing user-supplied dirs
  install.py
Labels: category:task

#803 Do reductions properly in tensor contraction tasks
  cunumeric_cpp.cmake
  src/cunumeric/matrix/contract.cc
  src/cunumeric/matrix/contract.cu
  src/cunumeric/matrix/contract_omp.cc
  src/cunumeric/matrix/contract_template.inl
  src/cunumeric/matrix/matmul.cc
  src/cunumeric/matrix/matmul.cu
  src/cunumeric/matrix/matmul_cpu.inl
  src/cunumeric/matrix/matmul_omp.cc
  src/cunumeric/matrix/matmul_template.inl
  src/cunumeric/matrix/matvecmul.cc
  src/cunumeric/matrix/matvecmul.cu
  src/cunumeric/matrix/matvecmul_cpu.inl
  src/cunumeric/matrix/matvecmul_omp.cc
  src/cunumeric/matrix/matvecmul_template.inl
  src/cunumeric/matrix/util.cc
  src/cunumeric/matrix/util.h
  src/cunumeric/matrix/util_omp.cc
  src/cunumeric/matrix/util_omp.h
Labels: category:bug-fix

#817 Avoid an internal use of np.result_type
  cunumeric/module.py
  tests/integration/test_linspace.py
Labels: category:task

#802 Preemptively convert to np.ndarray on NumPy fallback
  cunumeric/__init__.py
  cunumeric/array.py
  cunumeric/coverage.py
  cunumeric/fft/__init__.py
  cunumeric/linalg/__init__.py
  cunumeric/random/__init__.py
  cunumeric/utils.py
  tests/unit/cunumeric/test_coverage.py
Labels: category:improvement

#819 Fix a compilation issue introduced by 811
  src/cunumeric/matrix/util.cc
Labels: category:task

#820 Remove obsolete file
  src/cunumeric/matrix/util_omp.cc
Labels: category:task

#805 [WIP] Docs refresh
  .gitignore
  BUILD.md
  README.md
  cunumeric/runtime.py
  docs/cunumeric/source/BUILD.md
  docs/cunumeric/source/CONTRIBUTING.md
  docs/cunumeric/source/README.md
  docs/cunumeric/source/api/index.rst
  docs/cunumeric/source/api/settings.rst
  docs/cunumeric/source/comparison/index.rst
  docs/cunumeric/source/conf.py
  docs/cunumeric/source/developer/BUILD.md
  docs/cunumeric/source/developer/CONTRIBUTING.md
  docs/cunumeric/source/developer/index.rst
  docs/cunumeric/source/developer/testing.rst
  docs/cunumeric/source/index.rst
  docs/cunumeric/source/user/configuration.rst
  docs/cunumeric/source/user/index.rst
  docs/cunumeric/source/user/installation.rst
  docs/cunumeric/source/user/notebooks.rst
  docs/cunumeric/source/user/notebooks/black_scholes.ipynb
  docs/cunumeric/source/user/notebooks/cholesky.ipynb
  docs/cunumeric/source/user/notebooks/stencil.ipynb
  docs/cunumeric/source/user/usage.rst
  docs/cunumeric/source/versions.rst
Labels: category:documentation

#821 Fix handling of negative axis in np.repeat
  cunumeric/module.py
  tests/integration/test_repeat.py
Labels: category:bug-fix
