Repository nv-legate/cunumeric, pull requests merged in 2023-03, with the labels that each got.

#823 Remove support for python 3.8
  conda/conda-build/conda_build_config.yaml
  setup.cfg
  setup.py
Labels: category:task

#815 Remove exception throwing from RNG code
  src/cunumeric/random/bitgenerator_curand.inl
  src/cunumeric/random/bitgenerator_template.inl
  src/cunumeric/random/curand_help.h
  src/cunumeric/random/rand_util.h
  src/cunumeric/random/randutil/generator.cuh
  src/cunumeric/random/randutil/generator.h
  src/cunumeric/random/randutil/generator_create.inl
  src/cunumeric/random/randutil/generator_host.cc
  src/cunumeric/random/randutil/randutil.h
  src/cunumeric/random/randutil/randutil_impl.h
  tests/unit/cunumeric/test_coverage.py
Labels: category:improvement

#721 Fix for #720 (by @lightsighter)
  src/cunumeric/convolution/convolve_template.inl
Labels: category:bug-fix

#822 Changes for sphinx theme 0.13
  docs/cunumeric/source/conf.py
Labels: category:task

#826 Prune out old API references and update the url in README
  README.md
  docs/cunumeric/source/versions.rst
Labels: category:task

#825 Ensure unary_func seeding is deterministic across processes
  tests/integration/test_unary_ufunc.py
Labels: category:bug-fix

#827 Use the new registration callback API
  src/cunumeric/cunumeric.cc
Labels: category:task

#824 Pin legate to a specific commit
  .gitignore
  CMakeLists.txt
  cmake/thirdparty/get_legate_core.cmake
  cmake/versions.json
Labels: category:improvement

#831 Update BUILD.md
  BUILD.md
Labels: category:task

#832 Update BUILD.md (#831)
  BUILD.md
Labels: category:task

#830 Add support for Python 3.11
  conda/conda-build/conda_build_config.yaml
  conda/conda-build/meta.yaml
  setup.py
Labels: enhancement, category:improvement

#828 Enhance test on concatenate and stack APIs.
  cunumeric/module.py
  tests/integration/test_concatenate_stack.py
  tests/integration/test_vstack.py
Labels: category:task

#842 Use explicit task creation APIs
  cunumeric/deferred.py
  cunumeric/linalg/cholesky.py
  cunumeric/runtime.py
  cunumeric/sort.py
Labels: category:task

#841 Update python usage notes
  docs/cunumeric/source/user/usage.rst
Labels: category:task

#834 Add ufunc methods
  cunumeric/_ufunc/ufunc.py
  cunumeric/coverage.py
  tests/unit/cunumeric/test_coverage.py
Labels: category:improvement

#846 Switch to rapids-cmake 23.04 early
  CMakeLists.txt
Labels: category:task

#813 Testcase enhance split api
  tests/integration/test_split.py
Labels: category:task

#849 Catch up name changes in the API
  cmake/versions.json
  src/cunumeric/index/advanced_indexing_template.inl
  src/cunumeric/index/repeat_template.inl
  src/cunumeric/mapper.cc
  src/cunumeric/scan/scan_local_template.inl
  src/cunumeric/search/argwhere_template.inl
  src/cunumeric/search/nonzero_template.inl
  src/cunumeric/set/unique.cu
  src/cunumeric/sort/sort.cu
  src/cunumeric/sort/sort_cpu.inl
Labels: category:task

#848 Update the legate core commit hash
  cmake/versions.json
Labels: category:task

#845 Support of the `shape` argument in `empty_like()` & Co.
  cunumeric/module.py
  tests/integration/test_array_creation.py
Labels: category:improvement

#844 Fix bugs in concatenate and stack APIs.
  cunumeric/module.py
  tests/integration/test_concatenate_stack.py
Labels: category:bug-fix

#855 Update Conda build scripts
  conda/conda-build/conda_build_config.yaml
  conda/conda-build/meta.yaml
Labels: category:bug-fix

#854 Enhance test_putmask/trace/scan
  cunumeric/array.py
  tests/integration/test_putmask.py
  tests/integration/test_scan.py
  tests/integration/test_trace.py
Labels: category:task

#853 Add a linkcheck target to docs build
  CONTRIBUTING.md
  docs/cunumeric/Makefile
Labels: category:task

#859 Fixes #858
  cunumeric/array.py
Labels: category:bug-fix

#867 test_prod & test_reduce use allclose to compare float arrays
  tests/integration/test_prod.py
  tests/integration/test_reduction.py
Labels: category:task

#869 Also build CPU-only packages for haswell
  conda/conda-build/build.sh
Labels: category:bug-fix

#866 Fix concatenate and *stack APIs to support scalars(#818, #839)
  cunumeric/module.py
  tests/integration/test_concatenate_stack.py
Labels: category:bug-fix
