Repository nv-legate/cunumeric, pull requests merged in 2023-07, with the labels that each got.

#981 Bump legate.core version
  cmake/versions.json
Labels: category:task

#980 fixing putmask logic for scalar inputs
  src/cunumeric/index/putmask_template.inl
  tests/integration/test_putmask.py
Labels: category:bug-fix

#879 Move build instructions to sphinx docs
  BUILD.md
  README.md
  docs/cunumeric/source/_images/developer-build.png
  docs/cunumeric/source/developer/BUILD.md
  docs/cunumeric/source/developer/building.rst
  docs/cunumeric/source/developer/index.rst
Labels: category:task

#978 fixing cuda error
  src/cunumeric/unary/unary_red.cu
Labels: category:bug-fix

#988 Bump legate core to pin host compilers to 11.*
  cmake/versions.json
Labels: category:task

#986 Change arg to LLONG_MIN to make it consistent with python.
  src/cunumeric/arg.inl
Labels: category:bug-fix

#925 Sanitize unary reductions that have NaNs
  cunumeric/_unary_red_utils.py
  cunumeric/config.py
  cunumeric/deferred.py
  cunumeric/eager.py
  cunumeric/module.py
  cunumeric/settings.py
  docs/cunumeric/source/api/math.rst
  docs/cunumeric/source/api/sorting.rst
  src/cunumeric/cunumeric_c.h
  src/cunumeric/execution_policy/reduction/scalar_reduction.cuh
  src/cunumeric/execution_policy/reduction/scalar_reduction.h
  src/cunumeric/execution_policy/reduction/scalar_reduction_omp.h
  src/cunumeric/unary/scalar_unary_red_template.inl
  src/cunumeric/unary/unary_red.cc
  src/cunumeric/unary/unary_red.cu
  src/cunumeric/unary/unary_red_omp.cc
  src/cunumeric/unary/unary_red_util.h
  tests/integration/test_nan_reduction.py
  tests/integration/test_nanarg_reduction.py
  tests/unit/cunumeric/test_settings.py
Labels: category:new-feature

#983 Histogram Functionality
  cunumeric/config.py
  cunumeric/deferred.py
  cunumeric/eager.py
  cunumeric/module.py
  cunumeric/thunk.py
  cunumeric_cpp.cmake
  docs/cunumeric/source/api/statistics.rst
  src/cunumeric/cunumeric_c.h
  src/cunumeric/stat/histogram.cc
  src/cunumeric/stat/histogram.cu
  src/cunumeric/stat/histogram.cuh
  src/cunumeric/stat/histogram.h
  src/cunumeric/stat/histogram_cpu.h
  src/cunumeric/stat/histogram_gen.h
  src/cunumeric/stat/histogram_impl.h
  src/cunumeric/stat/histogram_omp.cc
  src/cunumeric/stat/histogram_template.inl
  tests/integration/test_histogram.py
  tests/unit/cunumeric/test_config.py
Labels: category:new-feature

#992 Fix Wundefined-var-template clang warning
  src/cunumeric/arg.inl
Labels: category:task

#990 improve random bitgenerator code coverage
  cunumeric/random/generator.py
  tests/integration/test_random_advanced.py
  tests/integration/test_random_beta.py
  tests/integration/test_random_bitgenerator.py
  tests/integration/test_random_creation.py
  tests/integration/test_random_gamma.py
  tests/integration/test_random_straightforward.py
Labels: category:task

#996 fixing versions in gh-pages
  22.05/versions.html
  22.08/versions.html
  22.10/versions.html
  23.01/versions.html
  23.03/versions.html
  23.07/versions.html
Labels: category:documentation

#999 Missing alignment on histogram call
  cunumeric/deferred.py
Labels: category:bug-fix

#1000 Missing alignment on histogram call
  cunumeric/deferred.py
Labels: category:bug-fix

#994 Updating version for docs
  cunumeric/_sphinxext/_comparison_config.py
  docs/cunumeric/source/versions.rst
Labels: category:documentation

#998 pin cuda-version
  conda/conda-build/meta.yaml
Labels: category:bug-fix

#1002 pin cuda-version
  conda/conda-build/meta.yaml
Labels: category:task

#1004 Bump up cunumeric version and legate.core version
  CMakeLists.txt
  cmake/versions.json
Labels: category:task

#1008 Fix file name in the CI workflow
  .github/workflows/ci-gh.yml
Labels: category:task
