Repository nv-legate/cunumeric, pull requests merged in 2023-11, with the labels that each got.

#1067 Fix #1065
  cmake/versions.json
  cunumeric/eager.py
Labels: category:bug-fix

#1068 Suggest using mamba over conda
  README.md
Labels: category:documentation

#1058 Missing CUDA libs are now included in main conda env get script
  continuous_integration/scripts/build-cunumeric-all
Labels: category:task

#1063 Typos
  scripts/util/build-caching.sh
Labels: category:task

#1072 Fixes #1069, #1070
  cmake/versions.json
  cunumeric/module.py
  tests/integration/test_einsum.py
Labels: category:bug-fix

#1029 Add batched cholesky implementation and tests
  cunumeric/config.py
  cunumeric/linalg/cholesky.py
  cunumeric/linalg/linalg.py
  cunumeric_cpp.cmake
  src/cunumeric/cunumeric_c.h
  src/cunumeric/mapper.cc
  src/cunumeric/matrix/batched_cholesky.cc
  src/cunumeric/matrix/batched_cholesky.cu
  src/cunumeric/matrix/batched_cholesky.h
  src/cunumeric/matrix/batched_cholesky_omp.cc
  src/cunumeric/matrix/batched_cholesky_template.inl
  src/cunumeric/matrix/potrf.cc
  src/cunumeric/matrix/potrf.cu
  src/cunumeric/matrix/potrf_omp.cc
  src/cunumeric/matrix/potrf_template.inl
  tests/integration/test_cholesky.py
  tests/unit/cunumeric/test_config.py
Labels: category:new-feature

#1073 Remove negative test that's now passing
  tests/integration/test_cholesky.py
Labels: category:task

#1074 adding v23.11 to documentation
  docs/cunumeric/source/versions.rst
Labels: category:documentation

#1071 Plumbing for np.ma
  cunumeric/__init__.py
  cunumeric/array.py
  cunumeric/ma/__init__.py
  cunumeric/ma/_masked_array.py
Labels: category:task

#1081 Fix #1079
  cunumeric/array.py
  tests/integration/test_set_item.py
Labels: category:bug-fix

#1082 Flip
  cunumeric/module.py
  docs/cunumeric/source/api/manipulation.rst
  tests/integration/test_flip.py
Labels: category:new-feature

#1083 Add more details to conda install process
  README.md
Labels: category:documentation

#1077 Don't instantiate template for low DIM counts, to fix a warning
  src/cunumeric/matrix/batched_cholesky_template.inl
Labels: category:task

#1088 removing unused variable in diagonal implementation
  cmake/versions.json
  cunumeric/array.py
  cunumeric/module.py
  tests/integration/test_index_routines.py
Labels: category:improvement

#1095 Update dependencies in meta.yaml
  .github/actions/download-artifacts/action.yml
  conda/conda-build/meta.yaml
Labels: category:task

#1086 Add convolve tests to improve c++ coverage
  tests/integration/test_convolve.py
Labels: category:task
