Repository nv-legate/cunumeric, pull requests merged in 2023-05, with the labels that each got.

#908 Improve matmul coverage and test bug fix
  tests/integration/test_matmul.py
Labels: category:task

#915 Revert "WAR for TBLIS compiler detection while upstream PR is pending (#890)"
  cmake/thirdparty/get_tblis.cmake
Labels: category:task

#905 Improve cunumeric.prod coverage and some test fixes
  tests/integration/test_extract.py
  tests/integration/test_prod.py
Labels: category:task

#728 Changes for resource scoping
  cmake/versions.json
  cunumeric/runtime.py
Labels: category:task

#911 Enhance test_logic.py and test_logical.py
  tests/integration/test_logic.py
  tests/integration/test_logical.py
Labels: category:task

#916 add negative test case test_searchedsorted.py
  tests/integration/test_searchsorted.py
Labels: category:task

#914 Update for Context-less annotations
  cunumeric/coverage.py
  cunumeric/deferred.py
Labels: category:task

#920 Fix unit tests
  cmake/versions.json
  cunumeric/utils.py
  tests/unit/cunumeric/test_config.py
  tests/unit/cunumeric/test_utils.py
Labels: category:bug-fix

#926 Enhance test_complex_ops.py and test_partition.py
  tests/integration/test_complex_ops.py
  tests/integration/test_partition.py
Labels: category:task

#927 Improve cunumeric.clip code coverage
  tests/integration/test_clip.py
Labels: category:task

#918 Improve cunumeric.diagonal code coverage
  tests/integration/test_index_routines.py
Labels: category:task

#929 Bump up legate to fix mypy errors
  cmake/versions.json
Labels: category:task

#923 Fix message on NaN errors in benchmarks
  examples/jacobi.py
  examples/logreg.py
Labels: category:task

#932 Bump legate.core version, for latest Legion bugfix
  cmake/versions.json
Labels: category:task

#935 Bump legate.core commit
  cmake/versions.json
Labels: category:task

#922 Unify LEGATE_TEST and CUNUMERIC_TEST
  cunumeric/linalg/cholesky.py
  cunumeric/runtime.py
  cunumeric/settings.py
  tests/unit/cunumeric/test_settings.py
Labels: category:task

#937 Update ingest example for new type system
  examples/ingest.py
Labels: category:task

#938 Bump legate.core version
  cmake/versions.json
Labels: category:task

#939 Docs for LEGION_DEFAULT_ARGS
  docs/cunumeric/source/user/usage.rst
Labels: category:task

#941 Use correct type, to avoid int narrowing
  src/cunumeric/index/advanced_indexing.cc
Labels: category:bug-fix

#899 Incorporating GH workflow from legate-separate-build-scripts.
  .github/workflows/ci-gh.yml
  continuous_integration/home/coder/.local/bin/build-cunumeric-conda
  continuous_integration/home/coder/.local/bin/build-cunumeric-cpp
  continuous_integration/home/coder/.local/bin/build-cunumeric-wheel
Labels: category:improvement

#865 adding new black scholes example
  examples/black_scholes_greeks.py
Labels: category:task

#943 Fix python fault handler variable in CI workflow
  .github/workflows/ci.yml
Labels: category:task

#934 Improve code coverage for array and trilu
  tests/integration/test_array.py
  tests/integration/test_trilu.py
  tests/integration/test_trilu_indices.py
Labels: category:task

#940 Fix cunumeric.arange issues
  cunumeric/module.py
  tests/integration/test_array_creation.py
  tests/integration/test_diag_indices.py
Labels: category:bug-fix

#945 Improve code coverage
  tests/integration/test_fill_diagonal.py
  tests/integration/test_put_along_axis.py
  tests/integration/test_reshape.py
  tests/integration/test_scan.py
Labels: category:task

#942 Use the right type for scalar arguments
  cmake/versions.json
  cunumeric/linalg/cholesky.py
Labels: category:bug-fix

#949 Bump Legate for the Realm DMA fix
  cmake/versions.json
Labels: category:task

#950 Bump Legate for the Realm DMA fix
  cmake/versions.json
Labels: category:task
