Repository nv-legate/cunumeric, pull requests merged in 2023-01, with the labels that each got.

#746 Switch docs from recommonmark to myst-parser
  README.md
  docs/cunumeric/source/conf.py
Labels: category:task

#747 Fix timing for CuPy tests
  examples/benchmark.py
  examples/black_scholes.py
  examples/cg.py
  examples/einsum.py
  examples/gemm.py
  examples/indexing_routines.py
  examples/jacobi.py
  examples/kmeans.py
  examples/kmeans_slow.py
  examples/kmeans_sort.py
  examples/linreg.py
  examples/logreg.py
  examples/lstm_backward.py
  examples/lstm_forward.py
  examples/lstm_full.py
  examples/richardson_lucy.py
  examples/scan.py
  examples/solve.py
  examples/sort.py
  examples/stencil.py
Labels: category:bug-fix

#748 Enhance test_inner.py and test_tensordot.py
  tests/integration/test_dot.py
  tests/integration/test_inner.py
  tests/integration/test_tensordot.py
Labels: category:task

#742 Testcase enhance test_bits.py and test_contains.py
  tests/integration/test_bits.py
  tests/integration/test_contains.py
Labels: category:task

#749 fix assertion in config test
  tests/unit/cunumeric/test_config.py
Labels: category:task

#751 adding new version for documentations
  docs/cunumeric/source/versions.rst
Labels: category:task

#753 Don't turn on cuNumeric debug checks on debug-rel builds
  cunumeric_cpp.cmake
Labels: category:bug-fix

#750 Pass `CMAKE_GENERATOR` to scikit-build
  install.py
Labels: category:improvement

#762 Change the default CPU architecture to haswell
  install.py
Labels: category:improvement

#765 Force conda version of cutensor
  conda/conda-build/meta.yaml
Labels: category:bug-fix

#766 handle numpy 'builtins' properly for coverage
  cunumeric/coverage.py
  cunumeric/random/__init__.py
Labels: category:bug-fix

#767 Unrestrict curand version
  conda/conda-build/meta.yaml
Labels: category:task

#770 Update the architectures built in conda package
  conda/conda-build/build.sh
Labels: category:improvement

#771 Update the architectures built in conda package (backport #770)
  conda/conda-build/build.sh
Labels: category:improvement

#755 Expose command args for legate driver help.
  cunumeric/__init__.py
  cunumeric/args.py
  cunumeric/runtime.py
Labels: category:task

#772 Revert "Update the architectures built in conda package (#770) (#771)"
  conda/conda-build/build.sh
Labels: category:task

#768 Rename setup to setup_method
  tests/integration/test_append.py
  tests/integration/test_array_creation.py
  tests/integration/test_flatten.py
  tests/integration/test_moveaxis.py
  tests/integration/test_put_along_axis.py
  tests/integration/test_take_along_axis.py
Labels: category:task

#774 pre-commit autoupdate
  .pre-commit-config.yaml
Labels: category:task

#764 Use @loader_path instead of $ORIGIN on MacOS
  cunumeric_cpp.cmake
Labels: category:task

#754 Testcase enhance test_nonzero.py and test_exp.py
  tests/integration/test_exp.py
  tests/integration/test_nonzero.py
  tests/integration/test_numpy_interop.py
Labels: category:task
