Repository nv-legate/cunumeric, pull requests merged in 2023-06, with the labels that each got.

#948 enhance test_einsum and test_einsum_path
  tests/integration/test_einsum.py
  tests/integration/test_einsum_path.py
Labels: category:task

#954 Adjust the iteration count for Black-Scholes example
  examples/black_scholes_greeks.py
Labels: category:task

#960 Remove cudatoolkit from conda metadata
  conda/conda-build/meta.yaml
Labels: category:task

#959 Fall back to NumPy eagerly on RandomState methods
  cunumeric/random/random.py
Labels: category:bug-fix

#962 enhance test_setflags
  tests/integration/test_repeat.py
  tests/integration/test_setflags.py
Labels: category:task

#963 Rev up the version in cmake
  CMakeLists.txt
  cmake/versions.json
Labels: category:bug-fix

#973 Resolve numpy 1.25 issues
  cunumeric/_ufunc/ufunc.py
  cunumeric/array.py
  cunumeric/linalg/linalg.py
  cunumeric/module.py
  tests/integration/test_binary_op_typing.py
Labels: category:bug-fix

#974 Updated versions.json to the latest legate.core SHA.
  cmake/versions.json
Labels: category:task

#759 Implement broadcast routines
  cunumeric/_ufunc/ufunc.py
  cunumeric/array.py
  cunumeric/deferred.py
  cunumeric/eager.py
  cunumeric/module.py
  cunumeric/thunk.py
  docs/cunumeric/source/api/broadcast.rst
  docs/cunumeric/source/api/classes.rst
  docs/cunumeric/source/api/manipulation.rst
  tests/integration/test_broadcast.py
  tests/integration/test_flags.py
  tests/integration/test_setflags.py
Labels: category:new-feature

#971 Set lib_dir explicitly to lib/, even on RHEL
  CMakeLists.txt
  cunumeric_cpp.cmake
  cunumeric_python.cmake
Labels: category:bug-fix

#968 Add tests for the input output related apis
  cunumeric/array.py
  tests/integration/test_input_output.py
Labels: category:task

#955 Add tests for random creation apis
  tests/integration/test_random_creation.py
Labels: category:task

#976 Fix docs breakage from np 1.25
  cunumeric/_sphinxext/_comparison_config.py
Labels: category:task

#977 Ensure ufunc/function dispatching is narrow
  cunumeric/array.py
  tests/integration/test_array_dunders.py
Labels: category:improvement
