Repository nv-legate/cunumeric, pull requests merged in 2023-08, with the labels that each got.

#1013 Improve fft code coverage
  tests/integration/test_fft_c2c.py
Labels: category:task

#1003 Histogram refactor
  src/cunumeric/stat/histogram.cc
  src/cunumeric/stat/histogram.cu
  src/cunumeric/stat/histogram.cuh
  src/cunumeric/stat/histogram_cpu.h
  src/cunumeric/stat/histogram_gen.h
  src/cunumeric/stat/histogram_impl.h
  src/cunumeric/stat/histogram_omp.cc
Labels: category:improvement

#1005 Fix for control replication violation in test
  tests/integration/test_advanced_indexing.py
  tests/integration/test_index_routines.py
  tests/integration/test_indices.py
  tests/integration/test_prod.py
  tests/integration/test_reduction.py
  tests/integration/test_trace.py
  tests/integration/utils/generators.py
Labels: category:bug-fix

#1014 fix build instructions link
  docs/cunumeric/source/developer/building.rst
  docs/cunumeric/source/user/installation.rst
Labels: category:bug-fix

#1015 Various test fixes
  tests/integration/test_random_advanced.py
  tests/integration/test_random_beta.py
  tests/integration/test_random_bitgenerator.py
  tests/integration/test_random_gamma.py
  tests/integration/test_random_straightforward.py
  tests/integration/test_reshape.py
Labels: category:task

#1017 Add back None as an accepted value for axis on some type sigs
  cunumeric/deferred.py
  cunumeric/eager.py
  cunumeric/module.py
  cunumeric/thunk.py
Labels: category:bug-fix

#1011 If a scalar ufunc arg is cn.ndarray use its type directly
  cunumeric/_ufunc/ufunc.py
Labels: category:bug-fix

#1019 More RNG test fixes for MacOS
  tests/integration/test_random_creation.py
Labels: category:task

#1007 Update to the latest Legion
  cmake/versions.json
  examples/black_scholes.py
  examples/cg.py
  examples/gemm.py
  examples/ingest.py
  examples/kmeans.py
  examples/kmeans_slow.py
  examples/kmeans_sort.py
  examples/linreg.py
  examples/logreg.py
Labels: category:task

#993 GH docker based reusable CI workflows.
  .dockerignore
  .github/workflows/ci-gh.yml
  .github/workflows/gh-build-and-test.yml
  .github/workflows/gh-build.yml
  .github/workflows/gh-cleanup.yml
  cmake/versions.json
  continuous_integration/Dockerfile
  continuous_integration/home/coder/.local/bin/build-cunumeric-all
  continuous_integration/home/coder/.local/bin/build-cunumeric-conda
Labels: category:task

#1024 Skip the docstrings for functions pulled from cloned modules
  cunumeric/coverage.py
  tests/unit/cunumeric/test_coverage.py
Labels: category:bug-fix

#664 Quantile Implementation
  cunumeric/module.py
  docs/cunumeric/source/api/statistics.rst
  examples/quantiles.py
  tests/integration/test_percentiles.py
  tests/integration/test_quantiles.py
Labels: category:new-feature

#1026 Ignore last-failed file
  .gitignore
Labels: category:task

#1033 Updated versions.json SHA.
  cmake/versions.json
Labels: category:task

#1035 Use `copy-pr-bot`
  .github/copy-pr-bot.yaml
  .github/ops-bot.yaml
Labels: category:task

#1037 Update pre-commit mypy
  .pre-commit-config.yaml
  pyproject.toml
Labels: category:task
