Repository nv-legate/cunumeric, pull requests merged in 2023-09, with the labels that each got.

#1038 enhance test_matrix_power.py/cholesky.py/norm.py
  cunumeric/linalg/exception.py
  cunumeric/linalg/linalg.py
  tests/integration/test_cholesky.py
  tests/integration/test_matrix_power.py
  tests/integration/test_norm.py
Labels: category:task

#1042 Don't cast histogram to int64 when density=True
  cunumeric/module.py
Labels: category:bug-fix

#1046 Explicitly cast result of shift binary operators
  src/cunumeric/binary/binary_op_util.h
Labels: category:bug-fix

#1044 Reject types that DeferredArray doesn't support
  cunumeric/array.py
  cunumeric/eager.py
  cunumeric/module.py
  cunumeric/runtime.py
  cunumeric/utils.py
  tests/integration/test_array.py
  tests/integration/test_astype.py
  tests/integration/test_atleast_nd.py
  tests/integration/test_fill.py
  tests/integration/test_fill_diagonal.py
  tests/integration/test_logic.py
  tests/integration/test_matmul.py
  tests/integration/test_repeat.py
  tests/integration/test_sort.py
  tests/integration/test_split.py
  tests/unit/cunumeric/test_utils.py
Labels: category:task

#1045 Remove use of deprecated np.find_common_type
  cunumeric/array.py
Labels: category:bug-fix

#1048 Add best practices info to sphinx docs
  docs/cunumeric/source/user/index.rst
  docs/cunumeric/source/user/practices.rst
Labels: category:improvement

#1043 Gh artifacts based CI
  .github/actions/download-artifacts/action.yml
  .github/workflows/ci-gh.yml
  .github/workflows/gh-build-and-test.yml
  .github/workflows/gh-build.yml
  .github/workflows/gh-cleanup.yml
  .github/workflows/gh-test.yml
  cmake/versions.json
  conda/conda-build/meta.yaml
  continuous_integration/Dockerfile
  continuous_integration/dot-gitconfig
  continuous_integration/home/coder/.local/bin/build-cunumeric-all
  continuous_integration/scripts/build-cunumeric-all
  continuous_integration/scripts/build-cunumeric-conda
  continuous_integration/scripts/build-cunumeric-cpp
  continuous_integration/scripts/build-cunumeric-wheel
  continuous_integration/scripts/entrypoint
  continuous_integration/scripts/test-cunumeric
Labels: category:task

#1051 Enable OpenMP tests in CI.
  .github/workflows/ci.yml
  .github/workflows/gh-build-and-test.yml
Labels: in progress, category:task

#1052 Update version to 23.11
  CMakeLists.txt
  cmake/versions.json
Labels: category:task
