Repository nv-legate/cunumeric, pull requests merged in 2024-02, with the labels that each got.

#1120 Update cuda version to 12.2
  .github/workflows/gh-build.yml
  cmake/versions.json
  continuous_integration/scripts/test-cunumeric
  tests/integration/test_overlap.py
Labels: in progress, category:improvement

#1117 Add np.digitize
  cunumeric/module.py
  tests/integration/test_digitize.py
Labels: category:new-feature

#1127 Bump Legate-Core version
  cmake/versions.json
  cunumeric/module.py
  docs/cunumeric/source/api/math.rst
  docs/cunumeric/source/api/statistics.rst
Labels: category:task

#1126 Basic np.load implementation, falling back to NumPy
  cunumeric/module.py
  docs/cunumeric/source/api/io.rst
  docs/cunumeric/source/api/routines.rst
Labels: category:new-feature

#1121 Nanquantile, Nanpercentile implementation
  cunumeric/module.py
  docs/cunumeric/source/api/statistics.rst
  tests/integration/test_file.py
  tests/integration/test_nanpercentiles.py
  tests/integration/test_nanquantiles.py
Labels: category:new-feature
